In [18]:
# Create a house price prediction model
# House price is determined by factors such as TAX, CRIME RATE, PROPERTY AGE ETC

In [29]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_boston as lb

In [20]:
# Load in the sklearn dataset
boston = lb()

In [21]:
# Create a data frame
df = pd.DataFrame(boston.data, columns=boston.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [25]:
# View target(House prices!) / per $ 10 000
boston.target[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

In [26]:
# Update price/target
price = boston.target * 10000
# Add price to dataframe
df["price"] = price

In [27]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT     price  
0     15.3  396.90   4.98  240000.0  
1     17.8  396.90   9.14  216000.0  
2     17.8  392.83   4.03  347000.0  
3     18.7  394.63   2.94  334000.0  
4     18.7  396.90   5.33  362000.0

In [30]:
x_values = df[["CRIM", "NOX", "AGE", "TAX", "RM"]]
y_values = df.price

In [172]:
# Create training and testing samples
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x_values, y_values, test_size = 0.2, random_state = 14)

In [173]:
# Create the linear model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [174]:
#Train model
model.fit(x_train, y_train)

LinearRegression()

In [175]:
model.predict(x_test)[: 5]

array([226828.45267734, 433343.15133633, 204141.44776935, 272342.45368685,
       211273.47868354])

In [176]:
y_test[: 5]

355    206000.0
225    500000.0
150    215000.0
70     242000.0
432    161000.0
Name: price, dtype: float64

In [177]:
model.score(x_test, y_test)

0.46768437491770065

In [216]:
condition = 0.0
x = 0
while condition < 0.90:
    x_train,x_test,y_train,y_test = train_test_split(x_values, y_values, test_size = 0.05, random_state = x)
    model.fit(x_train, y_train)
    condition = model.score(x_test, y_test)
    x+=1

print("done")

done


In [217]:
x

63685

In [218]:
condition

0.9218698990993346

In [224]:
# Save model
import joblib

modelName = 'Boston_model.pik'
joblib.dump(model, modelName)

['Boston_model.pik']

In [225]:
loaded_model = joblib.load(modelName)
result = loaded_model.score(x_test, y_test)
result

0.9218698990993346

In [226]:
model.predict(x_test[:5])

array([296526.27474365, 160423.89429842, 209656.14296487, 201966.34174947,
       246710.8631269 ])

In [227]:
x_test[:1]

CRIM    NOX   AGE    TAX     RM
275  0.09604  0.447  42.8  254.0  6.854

In [228]:
y_test[:5]

275    320000.0
496    197000.0
124    188000.0
54     189000.0
318    231000.0
Name: price, dtype: float64